In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("titanic_manipulate.csv")
df

       sex    age
0     male    NaN
1     male    NaN
2   female    NaN
3     male    NaN
4     male   0.83
5     male   0.92
6   female   0.75
7   female   0.75
8     male   0.67
9     male   0.42
10    male   0.83
11    male  54.00
12    male  47.00
13    male  20.00
14    male  18.00
15    male  21.00
16    male   8.00
17    male  25.00
18    male    NaN
19  female  63.00
20  female  30.00

In [ ]:
#THIS ONE DOES NOT WORK CAUSE ITS A GETTER WE GET A COPY OF THE OBJ
df.loc[18]["age"] = 25

/var/folders/sz/3_np9r_91db6_dhc9819tkwh0000gn/T/ipykernel_14153/1879718312.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df.loc[18]["age"] = 25

In [ ]:
df.loc[18,"age"] = 25 # THIS ONE WORKS CAUSE WE ACESS THE OBJ ITSELF

In [ ]:
df.loc[[2,3],"age"] = [12,29] #WE CAN ALSO DO A LOT OF VALUES AT THE SAME TIME

In [ ]:
df.fillna(round(df.))

       sex    age
0     male    NaN
1     male    NaN
2   female  12.00
3     male  29.00
4     male   0.83
5     male   0.92
6   female   0.75
7   female   0.75
8     male   0.67
9     male   0.42
10    male   0.83
11    male  54.00
12    male  47.00
13    male  20.00
14    male  18.00
15    male  21.00
16    male   8.00
17    male  25.00
18    male  25.00
19  female  63.00
20  female  30.00

In [ ]:
#this is the best way to do it!
df.loc[df["age"] < 1, "age"] = 1

## copy()

In [19]:
df = pd.read_csv("titanic_manipulate.csv")

In [13]:
df_copy = df

In [14]:
df_copy.fillna(100, inplace=True)

       sex     age
0     male  100.00
1     male  100.00
2   female  100.00
3     male  100.00
4     male    0.83
5     male    0.92
6   female    0.75
7   female    0.75
8     male    0.67
9     male    0.42
10    male    0.83
11    male   54.00
12    male   47.00
13    male   20.00
14    male   18.00
15    male   21.00
16    male    8.00
17    male   25.00
18    male  100.00
19  female   63.00
20  female   30.00

In [21]:
df_copy_with_copy = df.copy()

In [22]:
df_copy_with_copy.fillna(100, inplace=True)

       sex     age
0     male  100.00
1     male  100.00
2   female  100.00
3     male  100.00
4     male    0.83
5     male    0.92
6   female    0.75
7   female    0.75
8     male    0.67
9     male    0.42
10    male    0.83
11    male   54.00
12    male   47.00
13    male   20.00
14    male   18.00
15    male   21.00
16    male    8.00
17    male   25.00
18    male  100.00
19  female   63.00
20  female   30.00

In [23]:
df

       sex    age
0     male    NaN
1     male    NaN
2   female    NaN
3     male    NaN
4     male   0.83
5     male   0.92
6   female   0.75
7   female   0.75
8     male   0.67
9     male   0.42
10    male   0.83
11    male  54.00
12    male  47.00
13    male  20.00
14    male  18.00
15    male  21.00
16    male   8.00
17    male  25.00
18    male    NaN
19  female  63.00
20  female  30.00