<img align="center" src="https://iili.io/3wI8gI.png" style="height:90px" style="width:30px"/>

# Data Cleaning Lab | More Data, More Problems!

- You should follow a structured workflow when doing the data cleaning
    - Make use of headings and subheadings!



There is 1 column that should be dropped

Then there are 5 columns that needs cleaning. A column might require more than 1 step for the cleaning. Find what is wrong! 

*To finish this lab, you should find all the hidden errors and clean up the 5 columns*

# Read the csv file `sthlm_raw_lab.csv` and get started :)

In [3]:
import pandas as pd 
import numpy as np
import re

In [4]:

df = pd.read_csv("sthlm_raw_lab.csv")

In [5]:
df.head()

,Unnamed: 0,address,area,sqm,rooms,broker,monthly_fee,price_sold,date_sold,price_pct_change,street_id,street_name,city
0,0,"Gamla Brogatan 25, 2tr","Vasastan - City/Norrmalm,",114 sqm,"3,5",Fastighetsbyrån Stockholm - Vasastan,6769.0,7600000kr,Såld 13 april 2018,-5,475079,Gamla Brogatan,Stockholms kommun
1,1,"Gamla Brogatan 25, 2 tr","Vasastan- City/ Norrmalm,",71 sqm,2,Mäklarhuset Stockholm Innerstan,4696.0,5050000kr,Såld 23 juni 2016,4,475079,Gamla Brogatan,Stockholms kommun
2,2,Gamla Brogatan 25,"Vasastan- City/ Norrmalm,",102 sqm,4,Mäklarhuset Stockholm Innerstan,6519.0,6950000kr,Såld 29 april 2016,1,475079,Gamla Brogatan,Stockholms kommun
3,3,"Gamla Brogatan 25, 2tr","Vasastan - City/Norrmalm,",107 sqm,4,Fastighetsbyrån Stockholm - Vasastan,6713.0,7150000kr,Såld 26 november 2015,2,475079,Gamla Brogatan,Stockholms kommun
4,4,"Drottninggatan 114 A, 3 tr","Vasastan - Norrmalm,",90 sqm,3,Bostadsrättsspecialisten,3822.0,8900000kr,Såld 13 augusti 2020,0,475084,Drottninggatan,Stockholms kommun

In [6]:
df.drop(columns="Unnamed: 0",inplace=True)

## NEED TO CLEAN AREA SQM ROOMS PRICE SOLD, DATE, SOLD
 
 0   address           64469 non-null  str    
 1   area              63662 non-null  str    
 2   sqm               64238 non-null  str    
 3   rooms             64450 non-null  str    
 4   broker            64469 non-null  str    
 5   monthly_fee       64219 non-null  float64
 6   price_sold        64469 non-null  str    
 7   date_sold         64469 non-null  str    
 8   price_pct_change  64469 non-null  int64  
 9   street_id         64469 non-null  int64  
 10  street_name       62886 non-null  str    
 11  city              64469 non-null  str

## Cleaning Area

In [ ]:
def matching_adresses(df):

    ### string cleaner

    def clean_string(to_clean):
        for index,i in enumerate(list(to_clean)):
            try:
                int(i)
            except:
                continue
            return to_clean[:index-1]

    ### getting no area df 

    no_area_df = df.loc[df["area"].isna()][["area","address"]]
    no_area_df["address"] = no_area_df["address"].apply(clean_string)

    ### creating with area df

    with_area = df[["address","area"]].drop(no_area_df.index)
    with_area["address"] = with_area["address"].apply(clean_string)




    index_to_drop = []
    for index, _ in enumerate(range(0, (len(no_area_df)))):
        if no_area_df.iloc[index]["address"] in with_area["address"].values:
            df.loc[no_area_df.index[index], "area"] = with_area.loc[
                with_area["address"] == no_area_df.iloc[index]["address"]
                ].iloc[0]["area"]
        else:
            index_to_drop.append(no_area_df.index[index])

    df.drop(index_to_drop,inplace=True)

    return df

df = matching_adresses(df)

       # clean_string(no_area_lst.iloc[0]["address"]).isin(with_area.)

## Cleaning sqm

In [8]:
df.sqm.head()


df["sqm"] = df["sqm"].str.replace(r"[^0-9]", "", regex=True).astype("float")

In [9]:
df["sqm"]=df["sqm"].fillna(df["sqm"].mean())

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 64469 entries, 0 to 64468
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   address           64469 non-null  str
 1   area              64469 non-null  str
 2   sqm               64469 non-null  float64
 3   rooms             64450 non-null  str
 4   broker            64469 non-null  str
 5   monthly_fee       64219 non-null  float64
 6   price_sold        64469 non-null  str
 7   date_sold         64469 non-null  str
 8   price_pct_change  64469 non-null  int64
 9   street_id         64469 non-null  int64
 10  street_name       62886 non-null  str
 11  city              64469 non-null  str
dtypes: float64(2), int64(2), str(8)
memory usage: 5.9 MB

In [ ]:
df[["address","area"]]

## Cleaning rooms

In [11]:
df["rooms"] = df["rooms"].str.replace(",", ".").astype("float")

In [12]:
df["rooms"]=df["rooms"].fillna(df["rooms"].mean())

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 64469 entries, 0 to 64468
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   address           64469 non-null  str
 1   area              64469 non-null  str
 2   sqm               64469 non-null  float64
 3   rooms             64469 non-null  float64
 4   broker            64469 non-null  str
 5   monthly_fee       64219 non-null  float64
 6   price_sold        64469 non-null  str
 7   date_sold         64469 non-null  str
 8   price_pct_change  64469 non-null  int64
 9   street_id         64469 non-null  int64
 10  street_name       62886 non-null  str
 11  city              64469 non-null  str
dtypes: float64(3), int64(2), str(7)
memory usage: 5.9 MB

## Fixing price sold

In [54]:
df["price_sold"] = df["price_sold"].str.replace("kr", "").astype("float")

In [58]:
df.head()

,address,area,sqm,rooms,broker,monthly_fee,price_sold,date_sold,price_pct_change,street_id,street_name,city
0,"Gamla Brogatan 25, 2tr","Vasastan - City/Norrmalm,",114.0,3.5,Fastighetsbyrån Stockholm - Vasastan,6769.0,7600000.0,2018-04-13,-5,475079,Gamla Brogatan,Stockholms kommun
1,"Gamla Brogatan 25, 2 tr","Vasastan- City/ Norrmalm,",71.0,2.0,Mäklarhuset Stockholm Innerstan,4696.0,5050000.0,2016-06-23,4,475079,Gamla Brogatan,Stockholms kommun
2,Gamla Brogatan 25,"Vasastan- City/ Norrmalm,",102.0,4.0,Mäklarhuset Stockholm Innerstan,6519.0,6950000.0,2016-04-29,1,475079,Gamla Brogatan,Stockholms kommun
3,"Gamla Brogatan 25, 2tr","Vasastan - City/Norrmalm,",107.0,4.0,Fastighetsbyrån Stockholm - Vasastan,6713.0,7150000.0,2015-11-26,2,475079,Gamla Brogatan,Stockholms kommun
4,"Drottninggatan 114 A, 3 tr","Vasastan - Norrmalm,",90.0,3.0,Bostadsrättsspecialisten,3822.0,8900000.0,2020-08-13,0,475084,Drottninggatan,Stockholms kommun

## FIXING DATE SOLD

In [59]:
df["date_sold"] = df["date_sold"].str.replace("Såld ", "")
df.date_sold

AttributeError: Can only use .str accessor with string values, not datetime64

In [ ]:
month_map = {
    " januari ": "/1/", " februari ": "/2/", " mars ": "/3/", " april ": "/4/",
    " maj ": "/5/", " juni ": "/6/", " juli ": "/7/", " augusti ": "/8/",
    " september ": "/9/", " oktober ": "/10/", " november ": "/11/", " december ": "/12/"
}

df["date_sold"] = df["date_sold"].replace(month_map, regex=True)

In [ ]:
df["date_sold"] = pd.to_datetime(df["date_sold"], dayfirst=True)

In [ ]:
df.date_sold.head()

0   2018-04-13
1   2016-06-23
2   2016-04-29
3   2015-11-26
4   2020-08-13
Name: date_sold, dtype: datetime64[us]

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 64469 entries, 0 to 64468
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   address           64469 non-null  str
 1   area              64469 non-null  str
 2   sqm               64469 non-null  float64
 3   rooms             64469 non-null  float64
 4   broker            64469 non-null  str
 5   monthly_fee       64219 non-null  float64
 6   price_sold        64469 non-null  str
 7   date_sold         64469 non-null  datetime64[us]
 8   price_pct_change  64469 non-null  int64
 9   street_id         64469 non-null  int64
 10  street_name       62886 non-null  str
 11  city              64469 non-null  str
dtypes: datetime64[us](1), float64(3), int64(2), str(6)
memory usage: 5.9 MB

,address,area,sqm,rooms,broker,monthly_fee,price_sold,date_sold,price_pct_change,street_id,street_name,city
3635,Tegnérgatan 5,"Norrmalm,",92.0,3.0,Behrer & Partners,3746.0,11700000kr,2020-09-08,14,475246,NaN,Stockholms kommun
3636,Tegnérgatan 5A,"Vasastan - Östermalm,",34.0,2.0,Fastighetsbyrån Stockholm - Vasastan,1691.0,3800000kr,2020-09-01,12,475246,NaN,Stockholms kommun
3637,Tegnérgatan 10,"Vasastan,",66.0,2.0,BlumenthalHoffman Fastighetsmäkleri,2794.0,6900000kr,2020-08-30,15,475246,NaN,Stockholms kommun
3638,"Tegnérgatan 5 A, 2 tr","Vasastan / Norrmalm,",57.0,2.0,Eklund Stockholm New York,2352.0,5890000kr,2020-07-02,7,475246,NaN,Stockholms kommun
3639,"Tegnérgatan 55A, 2tr","Vasastan/Norrmalm,",355.0,2.0,Innerstadsspecialisten S AB,2284.0,3900000kr,2020-06-24,16,475246,NaN,Stockholms kommun
...,...,...,...,...,...,...,...,...,...,...,...,...
60977,Tegnérgatan 10,"City/Norrmalm,",41.0,1.5,Svensk Fastighetsförmedling,1820.0,2910000kr,2013-05-08,12,475246,NaN,Stockholms kommun
60978,"Tegnérgatan 57, BV","Vasastan,",29.0,1.0,Länsförsäkringar Fastighetsförmedling Stockhol...,2134.0,1775000kr,2013-05-07,-6,475246,NaN,Stockholms kommun
60979,"Tegnérgatan 55 C, 3 tr - SÅLD","Vasastan/Norrmalm,",78.0,3.0,Innerstadsspecialisten Stockholm AB,5379.0,4800000kr,2013-04-19,3,475246,NaN,Stockholms kommun
60980,"Tegnérgatan 57, 5 tr (hiss)","Vasastan, Norrmalm,",61.0,3.0,Svensk Fastighetsförmedling,4127.0,4050000kr,2013-04-19,7,475246,NaN,Stockholms kommun
60981,"Tegnérgatan 55A, 5 tr","Vasastan - City/Norrmalm,",35.0,1.5,Fastighetsbyrån Stockholm - Vasastan,2515.0,2400000kr,2013-04-12,5,475246,NaN,Stockholms kommun

In [ ]:
##df.loc[df["street_name"].isna()]["street"] = df.loc[df["street_name"].isna()]["address"].str.extract(r"^(.+?)\s+\d")[0]

In [ ]:
mask = df["street_name"].isna()
df.loc[df["street_name"].isna(), "street_name"] = (df.loc[mask, "address"].str.extract(r"^(.+?)(?:\s+\d|$)")[0])

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 64469 entries, 0 to 64468
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   address           64469 non-null  str
 1   area              64469 non-null  str
 2   sqm               64469 non-null  float64
 3   rooms             64469 non-null  float64
 4   broker            64469 non-null  str
 5   monthly_fee       64219 non-null  float64
 6   price_sold        64469 non-null  str
 7   date_sold         64469 non-null  datetime64[us]
 8   price_pct_change  64469 non-null  int64
 9   street_id         64469 non-null  int64
 10  street_name       64469 non-null  str
 11  city              64469 non-null  str
dtypes: datetime64[us](1), float64(3), int64(2), str(6)
memory usage: 5.9 MB

In [73]:
df.loc[df["monthly_fee"].isna()]
df[["monthly_fee","sqm"]].head(20)

    monthly_fee    sqm
0        6769.0  114.0
1        4696.0   71.0
2        6519.0  102.0
3        6713.0  107.0
4        3822.0   90.0
5        2787.0   56.0
6         712.0   36.0
7         460.0   46.0
8        1740.0  715.0
9        1362.0   45.0
10       2840.0   65.0
11       2880.0   66.0
12       1517.0   93.0
13       1567.0   92.0
14       4765.0  154.0
15       2223.0  115.0
16       1014.0   57.0
17       1257.0  465.0
18       1483.0   49.0
19       1400.0  715.0

In [84]:
filtered = df.loc[(df["area"] == "Vasastan,") & (~df["monthly_fee"].isna())][["monthly_fee","sqm"]]

avg_fee_psqm = filtered["monthly_fee"].sum() / filtered["sqm"].sum()

avg_fee_psqm

df.loc[df["monthly_fee"].isna(),"monthly_fee"] = df.loc[df["monthly_fee"].isna()]["sqm"] * avg_fee_psqm

In [82]:
idx_na = df.loc[df["monthly_fee"].isna(),"monthly_fee"].index

In [83]:
df.loc[idx_na, "sqm"]

1202      16.0
1339      14.0
1345      54.0
1361      14.0
1374      66.0
         ...
59823     42.0
60483    117.0
60484     78.0
60485     42.0
61668     60.0
Name: sqm, Length: 250, dtype: float64

In [79]:
df.loc[df["monthly_fee"].isna(), "sqm"] * avg_fee_psqm

1202      428.392867
1339      374.843758
1345     1445.825925
1361      374.843758
1374     1767.120575
            ...
59823    1124.531275
60483    3132.622838
60484    2088.415225
60485    1124.531275
61668    1606.473250
Name: sqm, Length: 250, dtype: float64

In [85]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 64469 entries, 0 to 64468
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   address           64469 non-null  str
 1   area              64469 non-null  str
 2   sqm               64469 non-null  float64
 3   rooms             64469 non-null  float64
 4   broker            64469 non-null  str
 5   monthly_fee       64469 non-null  float64
 6   price_sold        64469 non-null  float64
 7   date_sold         64469 non-null  datetime64[us]
 8   price_pct_change  64469 non-null  int64
 9   street_id         64469 non-null  int64
 10  street_name       64469 non-null  str
 11  city              64469 non-null  str
dtypes: datetime64[us](1), float64(4), int64(2), str(5)
memory usage: 5.9 MB