<img align="center" src="https://iili.io/3wI8gI.png" style="height:90px" style="width:30px"/>

# 02_pandas_index_objects

Import pandas and read the the `fifa_2018_players.csv` file into a `DataFrame`

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("fifa_2018_players.csv")

# Pt 1 - RangeIndex & BaseIndex
## Q1 
What type of index do we have?

In [4]:
df.index

RangeIndex(start=0, stop=736, step=1)

## Q2 
Using the loc-syntax, select the 25 first rows of the df

In [ ]:
df.loc[:24]

,team,number,position,birth_date,shirt_name,club,height,weight,league,age,name,caps
0,Argentina,1,GK,1986-02-10,GUZMÁN,Tigres UANL,192,90,MEX,32.339726,Nahuel Guzmán,6
1,Argentina,2,DF,1987-03-18,MERCADO,Sevilla FC,181,81,ESP,31.241096,Gabriel Mercado,20
2,Argentina,3,DF,1992-08-31,TAGLIAFICO,AFC Ajax,169,65,NED,25.786301,Nicolás Tagliafico,4
3,Argentina,4,DF,1986-09-20,NaN,Torino FC,181,73,ITA,31.731507,Cristian Ansaldi,5
4,Argentina,5,MF,1986-01-30,BIGLIA,AC Milan,175,73,ITA,32.369863,Lucas Biglia,57
5,Argentina,6,DF,1987-03-17,FAZIO,AS Roma,199,85,ITA,31.243836,Federico Fazio,9
6,Argentina,7,MF,1988-06-29,NaN,Sevilla FC,175,73,ESP,29.958904,Éver Banega,62
7,Argentina,8,DF,1991-10-28,ACUÑA,Sporting CP,172,77,POR,26.627397,Marcos Acuña,10
8,Argentina,9,FW,1987-12-10,HIGUAÍN,Juventus FC,184,75,ITA,30.509589,Gonzalo Higuaín,71
9,Argentina,10,FW,1987-06-24,MESSI,FC Barcelona,170,72,ESP,30.972603,Lionel Messi,124
10,Argentina,11,MF,1988-02-14,DI MARÍA,Paris Saint-Germain FC,178,75,FRA,30.328767,Ángel Di María,94
11,Argentina,12,GK,1986-10-16,ARMANI,CA River Plate,189,85,ARG,31.660274,Franco Armani,0
12,Argentina,13,MF,1992-12-15,MEZA,CA Independiente,180,76,ARG,25.495890,Maximiliano Meza,2
13,Argentina,14,DF,1984-06-08,MASCHERANO,Hebei China Fortune FC,174,73,CHN,34.016438,Javier Mascherano,143
14,Argentina,15,MF,1993-02-15,LANZINI,West Ham United FC,167,66,ENG,25.326027,Enzo Pérez,23
15,Argentina,16,DF,1990-03-20,ROJO,Manchester United FC,189,82,ENG,28.235616,Marcos Rojo,56
16,Argentina,17,DF,1988-02-12,OTAMENDI,Manchester City FC,181,81,ENG,30.334247,Nicolás Otamendi,54
17,Argentina,18,DF,1990-07-13,SALVIO,SL Benfica,167,69,POR,27.920548,Eduardo Salvio,9
18,Argentina,19,FW,1988-06-02,AGÜERO,Manchester City FC,172,74,ENG,30.032877,Sergio Agüero,85
19,Argentina,20,MF,1996-04-09,LO CELSO,Paris Saint-Germain FC,177,75,FRA,22.180822,Giovani Lo Celso,5
20,Argentina,21,FW,1993-11-15,DYBALA,Juventus FC,177,73,ITA,24.578082,Paulo Dybala,12
21,Argentina,22,MF,1996-01-21,PAVÓN,CA Boca Juniors,169,65,ARG,22.394521,Cristian Pavón,5
22,Argentina,23,GK,1981-09-28,CABALLERO,Chelsea FC,186,80,ENG,36.709589,Willy Caballero,3
23,Australia,1,GK,1992-04-08,RYAN,Brighton & Hove Albion FC,184,82,ENG,26.183562,Mathew Ryan,44
24,Australia,2,DF,1994-04-28,DEGENEK,Yokohama F-Marinos,187,85,JPN,24.128767,Milos Degenek,18

## Q3. 
Using the iloc-syntax, select the 25 last rows of the df

In [10]:
df.iloc[-23:]

,team,number,position,birth_date,shirt_name,club,height,weight,league,age,name,caps
713,Uruguay,1,GK,1986-06-16,F. MUSLERA,Galatasaray SK,190,74,TUR,31.994521,Fernando Muslera,97
714,Uruguay,2,DF,1995-01-20,J.M. GIMENEZ,Atletico Madrid,185,77,ESP,23.397260,José Giménez,42
715,Uruguay,3,DF,1986-02-16,D. GODIN,Atletico Madrid,185,73,ESP,32.323288,Diego Godín,116
716,Uruguay,4,DF,1993-03-24,G. VARELA,CA Penarol,173,70,URU,25.224658,Guillermo Varela,3
717,Uruguay,5,MF,1984-12-02,C. SANCHEZ,CF Monterrey,171,74,MEX,33.531507,Carlos Sánchez,36
718,Uruguay,6,MF,1997-06-25,R. BENTANCUR,Juventus FC,187,73,ITA,20.969863,Rodrigo Bentancur,7
719,Uruguay,7,MF,1985-09-30,C. RODRIGUEZ,CA Penarol,178,79,URU,32.704110,Cristian Rodríguez,105
720,Uruguay,8,MF,1995-12-28,N. NANDEZ,CA Boca Juniors,171,61,ARG,22.460274,Nahitan Nández,12
721,Uruguay,9,FW,1987-01-24,L. SUAREZ,FC Barcelona,182,85,ESP,31.386301,Luis Suárez,98
722,Uruguay,10,FW,1994-06-01,G. DE ARRASCAETA,Cruzeiro EC,172,64,BRA,24.035616,Giorgian De Arrascaeta,14
723,Uruguay,11,FW,1986-10-12,C. STUANI,Girona FC,186,78,ESP,31.671233,Cristhian Stuani,41
724,Uruguay,12,GK,1989-05-29,M. CAMPAÑA,CA Independiente,184,79,ARG,29.043836,Martín Campaña,1
725,Uruguay,13,DF,1994-03-05,G. SILVA,CA Independiente,185,74,ARG,24.276712,Gastón Silva,17
726,Uruguay,14,MF,1996-02-11,L. TORREIRA,UC Sampdoria,168,61,ITA,22.336986,Lucas Torreira,3
727,Uruguay,15,MF,1991-08-24,M. VECINO,FC Internazionale,189,80,ITA,26.805479,Matías Vecino,22
728,Uruguay,16,DF,1984-06-08,M. PEREIRA,FC Porto,173,73,POR,34.016438,Maxi Pereira,125
729,Uruguay,17,MF,1993-02-07,D. LAXALT,Genoa CFC,178,66,ITA,25.347945,Diego Laxalt,6
730,Uruguay,18,FW,1996-08-14,M. GOMEZ,Celta Vigo,186,85,ESP,21.832877,Maxi Gómez,5
731,Uruguay,19,DF,1990-10-07,S. COATES,Sporting CP,196,89,POR,27.684932,Sebastián Coates,30
732,Uruguay,20,FW,1990-03-19,J. URRETAVISCAYA,CF Monterrey,172,66,MEX,28.238356,Jonathan Urretaviscaya,4
733,Uruguay,21,FW,1987-02-14,E. CAVANI,Paris Saint-Germain FC,188,78,FRA,31.328767,Edinson Cavani,101
734,Uruguay,22,DF,1987-04-07,M. CACERES,SS Lazio,178,75,ITA,31.186301,Martín Cáceres,76
735,Uruguay,23,GK,1983-03-25,M. SILVA,CR Vasco da Gama,187,82,BRA,35.221918,Martín Silva,11

## Q4
Using the loc-syntax, select the rows 3, 5 and 10 and only the age and team columns

In [18]:
df[["age","club"]].loc[[3,5,10]]

          age                    club
3   31.731507               Torino FC
5   31.243836                 AS Roma
10  30.328767  Paris Saint-Germain FC

## Q5
Set the "club" column as the new index of your df (save the change!)

In [ ]:
df.set_index("club", inplace=True)

## Q6 
Now, what type of index do we have?

In [ ]:
#string index

## Q7 
7. Check whether the new index contains only unique values (no duplicates)! Is this the case?

In [ ]:
index_repeated = df.index.duplicated(keep="first")
(~df.index.duplicated(keep="first")).sum()

#THERE ARE DUPLICATED

np.int64(310)

## Q8 
Get the frequency of all unique values in the index! What is the most frequent value?

In [32]:
df.index.value_counts().iloc[:1]

club
Manchester City FC    16
Name: count, dtype: int64

## Q9 
Reset the index to a RangeIndex and save the change.

In [35]:
df.reset_index(inplace=True)

# Part 2 - MultiIndex
## Q1
Create a MultiIndex for your df with `team` as the outer level and `position` as the inner level.

In [ ]:
df.set_index(["team", "position"])
#df.set_index(pd.MultiIndex.from_frame(df[["team", "position"]]))

                    index                    club       team  number position  \
team      position
Argentina GK            0             Tigres UANL  Argentina       1       GK
          DF            1              Sevilla FC  Argentina       2       DF
          DF            2                AFC Ajax  Argentina       3       DF
          DF            3               Torino FC  Argentina       4       DF
          MF            4                AC Milan  Argentina       5       MF
...                   ...                     ...        ...     ...      ...
Uruguay   DF          731             Sporting CP    Uruguay      19       DF
          FW          732            CF Monterrey    Uruguay      20       FW
          FW          733  Paris Saint-Germain FC    Uruguay      21       FW
          DF          734                SS Lazio    Uruguay      22       DF
          GK          735        CR Vasco da Gama    Uruguay      23       GK

                    birth_date        shirt_name  height  weight league  \
team      position
Argentina GK        1986-02-10            GUZMÁN     192      90    MEX
          DF        1987-03-18           MERCADO     181      81    ESP
          DF        1992-08-31        TAGLIAFICO     169      65    NED
          DF        1986-09-20               NaN     181      73    ITA
          MF        1986-01-30            BIGLIA     175      73    ITA
...                        ...               ...     ...     ...    ...
Uruguay   DF        1990-10-07         S. COATES     196      89    POR
          FW        1990-03-19  J. URRETAVISCAYA     172      66    MEX
          FW        1987-02-14         E. CAVANI     188      78    FRA
          DF        1987-04-07        M. CACERES     178      75    ITA
          GK        1983-03-25          M. SILVA     187      82    BRA

                          age                    name  caps
team      position
Argentina GK        32.339726           Nahuel Guzmán     6
          DF        31.241096         Gabriel Mercado    20
          DF        25.786301      Nicolás Tagliafico     4
          DF        31.731507        Cristian Ansaldi     5
          MF        32.369863            Lucas Biglia    57
...                       ...                     ...   ...
Uruguay   DF        27.684932        Sebastián Coates    30
          FW        28.238356  Jonathan Urretaviscaya     4
          FW        31.328767          Edinson Cavani   101
          DF        31.186301          Martín Cáceres    76
          GK        35.221918            Martín Silva    11

[736 rows x 13 columns]

In [ ]:
#index = pd.MultiIndex.from_frame(df[["team", "position"]])
#index

MultiIndex([('Argentina', 'GK'),
            ('Argentina', 'DF'),
            ('Argentina', 'DF'),
            ('Argentina', 'DF'),
            ('Argentina', 'MF'),
            ('Argentina', 'DF'),
            ('Argentina', 'MF'),
            ('Argentina', 'DF'),
            ('Argentina', 'FW'),
            ('Argentina', 'FW'),
            ...
            (  'Uruguay', 'MF'),
            (  'Uruguay', 'MF'),
            (  'Uruguay', 'DF'),
            (  'Uruguay', 'MF'),
            (  'Uruguay', 'FW'),
            (  'Uruguay', 'DF'),
            (  'Uruguay', 'FW'),
            (  'Uruguay', 'FW'),
            (  'Uruguay', 'DF'),
            (  'Uruguay', 'GK')],
           names=['team', 'position'], length=736)

## Q2 
Sort the index & save the change

In [45]:
df.set_index(["team", "position"], inplace=True)

## Q3
3.1 Select all players play for Sweden

In [46]:
df.loc["Sweden"]

,index,club,number,birth_date,shirt_name,height,weight,league,age,name,caps
position,,,,,,,,,,,
GK,644,FC Kobenhavn,1,1990-01-08,OLSEN,198,89,DEN,28.430137,Robin Olsen,18
DF,645,Celtic FC,2,1986-12-13,NaN,189,77,SCO,31.501370,Mikael Lustig,66
DF,646,Manchester United FC,3,1994-07-17,LINDELÖF,187,81,ENG,23.909589,Victor Lindelöf,21
DF,647,FC Krasnodar,4,1985-04-16,GRANQVIST,192,84,RUS,33.161644,Andreas Granqvist,72
DF,648,Swansea City AFC,5,1988-05-17,OLSSON,177,81,WAL,30.076712,Martin Olsson,43
DF,649,SV Werder Bremen,6,1994-04-21,NaN,181,76,GER,24.147945,Ludwig Augustinsson,15
MF,650,Hull City FC,7,1985-06-06,LARSSON,178,70,ENG,33.021918,Sebastian Larsson,100
MF,651,Hamburger SV,8,1989-07-28,EKDAL,186,75,GER,28.879452,Albin Ekdal,34
FW,652,Al Ain FC,9,1986-08-17,BERG,183,76,UAE,31.824658,Marcus Berg,57
MF,653,RB Leipzig,10,1991-10-23,FORSBERG,179,78,GER,26.641096,Emil Forsberg,36
FW,654,Deportivo Alavés,11,1992-04-15,GUIDETTI,185,79,ESP,26.164384,John Guidetti,20
GK,655,EA Guingamp,12,1990-01-28,JOHNSSON,187,83,FRA,28.375342,Karl-Johan Johnsson,5
MF,656,Seattle Sounders FC,13,1987-02-07,SVENSSON,183,77,USA,31.347945,Gustav Svensson,13
DF,657,Bologna FC,14,1993-04-22,HELANDER,192,83,ITA,25.145205,Filip Helander,4
MF,658,Genoa CFC,15,1992-06-28,HILJEMARK,184,73,ITA,25.961644,Oscar Hiljemark,22
DF,659,Bologna FC,16,1994-08-02,KRAFTH,181,72,ITA,23.865753,Emil Krafth,13
MF,660,FC Krasnodar,17,1992-01-02,CLAESSON,183,79,RUS,26.446575,Viktor Claesson,22
DF,661,Leeds United FC,18,1991-02-13,JANSSON,194,89,ENG,27.331507,Pontus Jansson,15
MF,662,FC Crotone,19,1991-05-11,ROHDÉN,182,76,ITA,27.093151,Marcus Rohdén,12
FW,663,Toulouse FC,20,1986-07-03,TOIVONEN,192,78,FRA,31.947945,Ola Toivonen,59
MF,664,Toulouse FC,21,1989-03-22,DURMAZ,180,69,FRA,29.230137,Jimmy Durmaz,45
FW,665,KV Waasland-Beveren,22,1992-06-24,NaN,189,83,BEL,25.972603,Isaac Kiese Thelin,20
GK,666,Swansea City AFC,23,1989-06-23,NORDFELDT,190,85,WAL,28.975342,Kristoffer Nordfeldt,8

/var/folders/sz/3_np9r_91db6_dhc9819tkwh0000gn/T/ipykernel_6326/2037383987.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  df.loc["Sweden","DF"]

                 index                  club  number  birth_date shirt_name  \
team   position
Sweden DF          645             Celtic FC       2  1986-12-13        NaN
       DF          646  Manchester United FC       3  1994-07-17   LINDELÖF
       DF          647          FC Krasnodar       4  1985-04-16  GRANQVIST
       DF          648      Swansea City AFC       5  1988-05-17     OLSSON
       DF          649      SV Werder Bremen       6  1994-04-21        NaN
       DF          657            Bologna FC      14  1993-04-22   HELANDER
       DF          659            Bologna FC      16  1994-08-02     KRAFTH
       DF          661       Leeds United FC      18  1991-02-13    JANSSON

                 height  weight league        age                 name  caps
team   position
Sweden DF           189      77    SCO  31.501370        Mikael Lustig    66
       DF           187      81    ENG  23.909589      Victor Lindelöf    21
       DF           192      84    RUS  33.161644    Andreas Granqvist    72
       DF           177      81    WAL  30.076712        Martin Olsson    43
       DF           181      76    GER  24.147945  Ludwig Augustinsson    15
       DF           192      83    ITA  25.145205       Filip Helander     4
       DF           181      72    ITA  23.865753          Emil Krafth    13
       DF           194      89    ENG  27.331507       Pontus Jansson    15

3.2 Select Swedish players play the position DF

In [ ]:
df.loc["Sweden","DF"]

## Q4
Select Swedish players play positions of MF and FW.

In [53]:
df.loc["Sweden"].loc[["MF", "FW"]]

,index,club,number,birth_date,shirt_name,height,weight,league,age,name,caps
position,,,,,,,,,,,
MF,650,Hull City FC,7,1985-06-06,LARSSON,178,70,ENG,33.021918,Sebastian Larsson,100
MF,651,Hamburger SV,8,1989-07-28,EKDAL,186,75,GER,28.879452,Albin Ekdal,34
MF,653,RB Leipzig,10,1991-10-23,FORSBERG,179,78,GER,26.641096,Emil Forsberg,36
MF,656,Seattle Sounders FC,13,1987-02-07,SVENSSON,183,77,USA,31.347945,Gustav Svensson,13
MF,658,Genoa CFC,15,1992-06-28,HILJEMARK,184,73,ITA,25.961644,Oscar Hiljemark,22
MF,660,FC Krasnodar,17,1992-01-02,CLAESSON,183,79,RUS,26.446575,Viktor Claesson,22
MF,662,FC Crotone,19,1991-05-11,ROHDÉN,182,76,ITA,27.093151,Marcus Rohdén,12
MF,664,Toulouse FC,21,1989-03-22,DURMAZ,180,69,FRA,29.230137,Jimmy Durmaz,45
FW,652,Al Ain FC,9,1986-08-17,BERG,183,76,UAE,31.824658,Marcus Berg,57
FW,654,Deportivo Alavés,11,1992-04-15,GUIDETTI,185,79,ESP,26.164384,John Guidetti,20
FW,663,Toulouse FC,20,1986-07-03,TOIVONEN,192,78,FRA,31.947945,Ola Toivonen,59
FW,665,KV Waasland-Beveren,22,1992-06-24,NaN,189,83,BEL,25.972603,Isaac Kiese Thelin,20

## Q5
Select the columns "height" and "weight" for players from team Germany and play the position of DF and GK.

In [55]:
df[["height","weight"]].loc["Germany"].loc[["DF", "GK"]]

          height  weight
position
DF           181      76
DF           185      75
DF           189      85
DF           192      90
DF           195      89
DF           191      85
DF           192      90
DF           176      72
GK           193      93
GK           189      88
GK           187      85

# Good job, lab finished
___
# Bonus Challenges
## Bonus 1 

Select all French players who play the position MF & DF and calculate the mean age.

In [65]:
round(float(df.loc["France"].loc[["MF", "DF"],"age"].mean()),3)

25.873

## Bonus 2

Players from Argentina are older for all positions in the data set compared to players from Nigeria. You are now asked to find out for which position shows the biggest age differenceand for which  which position shows the smallest age difference between the two countries.

Solve this using group by and unstack!

In [88]:
my_df = df[["age"]].loc[["Nigeria","Argentina"]].groupby(["position","team"]).mean().unstack()

In [89]:
my_df["age", "Argentina"] - my_df["age", "Nigeria"]

position
DF    4.047641
FW    3.582192
GK    6.384475
MF    0.545793
dtype: float64