# Data Cleaning | 6 recommended steps

- 1) First inspection - Get an overview of your data



- 2) Handle inconsistent or irrelevant data



- 3) Type conversion



- 4) Missing Values
    - drop or impute?



- 5) Duplicates



- 6) Outliers

In [20]:
import pandas as pd

In [21]:
df = pd.read_csv("titanic_imp.csv")

## 2. Handle inconsistet and/or irrelevant data

In [22]:
df

    Survived  Class  Gender   Age  SipSp  ParCh      Fare Emb Deck
0          0      3    male  22.0      1      0     $7.25   S  NaN
1          1      1  female  38.0      1      0  $71.2833   C    C
2          1      3  female  26.0      0      0    $7.925   S  NaN
3          1      1  female  35.0      1      0     $53.1   S    C
4          0      3    male  35.0      0      0     $8.05   S  NaN
..       ...    ...     ...   ...    ...    ...       ...  ..  ...
889        1      1    male  26.0      0      0     $30.0   C    C
890        0      3    male  32.0      0      0     $7.75   Q  NaN
891        0      2    male  24.0      0      0     $10.5   S  NaN
892        0      3    male  34.0      1      1     $14.4   S  NaN
893        0      3    male  36.0      0      0   $7.8958   S  NaN

[894 rows x 9 columns]

In [23]:
df["Fare"] = df["Fare"].str.replace("$","")

In [24]:
df.Fare.head()

0       7.25
1    71.2833
2      7.925
3       53.1
4       8.05
Name: Fare, dtype: str

In [25]:
df.describe(include="O")

/var/folders/sz/3_np9r_91db6_dhc9819tkwh0000gn/T/ipykernel_24988/504318277.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="O")

       Survived Gender           Age  Fare  Emb Deck
count       894    894           758   894  892  203
unique        4      2            92   248    3    7
top           0   male  Missing Data  8.05    S    C
freq        551    580            41    43  647   59

In [26]:
df.Survived.unique()

<StringArray>
['0', '1', 'yes', 'no']
Length: 4, dtype: str

In [30]:
#df.Survived.replace(to_replace=["yes","no"], value = ["1","0"],inplace=True)
df.replace({"Survived": {"yes": 1, "no": 0}}, inplace=True)

    Survived  Class  Gender   Age  SipSp  ParCh     Fare Emb Deck
0          0      3    male  22.0      1      0     7.25   S  NaN
1          1      1  female  38.0      1      0  71.2833   C    C
2          1      3  female  26.0      0      0    7.925   S  NaN
3          1      1  female  35.0      1      0     53.1   S    C
4          0      3    male  35.0      0      0     8.05   S  NaN
..       ...    ...     ...   ...    ...    ...      ...  ..  ...
889        1      1    male  26.0      0      0     30.0   C    C
890        0      3    male  32.0      0      0     7.75   Q  NaN
891        0      2    male  24.0      0      0     10.5   S  NaN
892        0      3    male  34.0      1      1     14.4   S  NaN
893        0      3    male  36.0      0      0   7.8958   S  NaN

[894 rows x 9 columns]

In [31]:
df.Survived.unique()

array(['0', '1', 1, 0], dtype=object)

## 3. Changing the data type with astype()

In [38]:
df.Survived = df.Survived.astype("int")
df.Fare = df.Fare.astype("float")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 894 entries, 0 to 893
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  894 non-null    int64
 1   Class     894 non-null    int64
 2   Gender    894 non-null    str
 3   Age       758 non-null    str
 4   SipSp     894 non-null    int64
 5   ParCh     894 non-null    int64
 6   Fare      894 non-null    float64
 7   Emb       892 non-null    str
 8   Deck      203 non-null    str
dtypes: float64(1), int64(4), str(4)
memory usage: 63.0 KB

In [40]:
df.Age.value_counts(dropna=False)

Age
NaN             136
Missing Data     41
24.0             31
22.0             27
18.0             26
               ...
0.67              1
250               1
0.42              1
34.5              1
74.0              1
Name: count, Length: 93, dtype: int64

In [41]:
import numpy as np

In [42]:
df.replace({"Age":{"Missing Data": np.nan}},inplace=True)

     Survived  Class  Gender   Age  SipSp  ParCh     Fare Emb Deck
0           0      3    male  22.0      1      0   7.2500   S  NaN
1           1      1  female  38.0      1      0  71.2833   C    C
2           1      3  female  26.0      0      0   7.9250   S  NaN
3           1      1  female  35.0      1      0  53.1000   S    C
4           0      3    male  35.0      0      0   8.0500   S  NaN
..        ...    ...     ...   ...    ...    ...      ...  ..  ...
889         1      1    male  26.0      0      0  30.0000   C    C
890         0      3    male  32.0      0      0   7.7500   Q  NaN
891         0      2    male  24.0      0      0  10.5000   S  NaN
892         0      3    male  34.0      1      1  14.4000   S  NaN
893         0      3    male  36.0      0      0   7.8958   S  NaN

[894 rows x 9 columns]

In [45]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 894 entries, 0 to 893
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  894 non-null    int64
 1   Class     894 non-null    int64
 2   Gender    894 non-null    str
 3   Age       717 non-null    str
 4   SipSp     894 non-null    int64
 5   ParCh     894 non-null    int64
 6   Fare      894 non-null    float64
 7   Emb       892 non-null    str
 8   Deck      203 non-null    str
dtypes: float64(1), int64(4), str(4)
memory usage: 63.0 KB

## Remove missing values with `dropna()`

In [44]:
df.dropna()

     Survived  Class  Gender   Age  SipSp  ParCh     Fare Emb Deck
1           1      1  female  38.0      1      0  71.2833   C    C
3           1      1  female  35.0      1      0  53.1000   S    C
6           0      1    male  54.0      0      0  51.8625   S    E
10          1      3  female   4.0      1      1  16.7000   S    G
11          1      1  female  58.0      0      0  26.5500   S    C
..        ...    ...     ...   ...    ...    ...      ...  ..  ...
871         1      1  female  47.0      1      1  52.5542   S    D
872         0      1    male  33.0      0      0   5.0000   S    B
879         1      1  female  56.0      0      1  83.1583   C    C
887         1      1  female  19.0      0      0  30.0000   S    B
889         1      1    male  26.0      0      0  30.0000   C    C

[182 rows x 9 columns]

In [46]:
df.dropna(thresh=8)

     Survived  Class  Gender   Age  SipSp  ParCh     Fare Emb Deck
0           0      3    male  22.0      1      0   7.2500   S  NaN
1           1      1  female  38.0      1      0  71.2833   C    C
2           1      3  female  26.0      0      0   7.9250   S  NaN
3           1      1  female  35.0      1      0  53.1000   S    C
4           0      3    male  35.0      0      0   8.0500   S  NaN
..        ...    ...     ...   ...    ...    ...      ...  ..  ...
889         1      1    male  26.0      0      0  30.0000   C    C
890         0      3    male  32.0      0      0   7.7500   Q  NaN
891         0      2    male  24.0      0      0  10.5000   S  NaN
892         0      3    male  34.0      1      1  14.4000   S  NaN
893         0      3    male  36.0      0      0   7.8958   S  NaN

[736 rows x 9 columns]

In [48]:
df.Age = df.Age.astype("float")

In [ ]:
df.Age = df.Age.fillna(df.Age.mean())

In [51]:
df.Emb.mode()

0    S
Name: Emb, dtype: str

In [53]:
df.replace({"Emb":{np.nan: df.Emb.mode()[0]}})

     Survived  Class  Gender   Age  SipSp  ParCh     Fare Emb Deck
0           0      3    male  22.0      1      0   7.2500   S  NaN
1           1      1  female  38.0      1      0  71.2833   C    C
2           1      3  female  26.0      0      0   7.9250   S  NaN
3           1      1  female  35.0      1      0  53.1000   S    C
4           0      3    male  35.0      0      0   8.0500   S  NaN
..        ...    ...     ...   ...    ...    ...      ...  ..  ...
889         1      1    male  26.0      0      0  30.0000   C    C
890         0      3    male  32.0      0      0   7.7500   Q  NaN
891         0      2    male  24.0      0      0  10.5000   S  NaN
892         0      3    male  34.0      1      1  14.4000   S  NaN
893         0      3    male  36.0      0      0   7.8958   S  NaN

[894 rows x 9 columns]

In [ ]:
df.drop(columns="Deck",inplace=True)

In [56]:
df.columns

Index(['Survived', 'Class', 'Gender', 'Age', 'SipSp', 'ParCh', 'Fare', 'Emb'], dtype='str')

## 5. Duplicates

In [57]:
df.loc[df.duplicated()]

     Survived  Class  Gender        Age  SipSp  ParCh     Fare Emb
47          1      3  female  30.718508      0      0   7.7500   Q
76          0      3    male  30.718508      0      0   7.8958   S
77          0      3    male  30.718508      0      0   8.0500   S
87          0      3    male  30.718508      0      0   8.0500   S
95          0      3    male  30.718508      0      0   8.0500   S
..        ...    ...     ...        ...    ...    ...      ...  ..
884         0      3    male  25.000000      0      0   7.0500   S
886         0      2    male  27.000000      0      0  13.0000   S
891         0      2    male  24.000000      0      0  10.5000   S
892         0      3    male  34.000000      1      1  14.4000   S
893         0      3    male  36.000000      0      0   7.8958   S

[114 rows x 8 columns]

In [58]:
df.drop([77,87])

     Survived  Class  Gender   Age  SipSp  ParCh     Fare Emb
0           0      3    male  22.0      1      0   7.2500   S
1           1      1  female  38.0      1      0  71.2833   C
2           1      3  female  26.0      0      0   7.9250   S
3           1      1  female  35.0      1      0  53.1000   S
4           0      3    male  35.0      0      0   8.0500   S
..        ...    ...     ...   ...    ...    ...      ...  ..
889         1      1    male  26.0      0      0  30.0000   C
890         0      3    male  32.0      0      0   7.7500   Q
891         0      2    male  24.0      0      0  10.5000   S
892         0      3    male  34.0      1      1  14.4000   S
893         0      3    male  36.0      0      0   7.8958   S

[892 rows x 8 columns]

In [59]:
df.Age.nlargest()

453    490.0
785    250.0
217    102.0
630     80.0
851     74.0
Name: Age, dtype: float64

In [61]:
df.loc[[785, 453], "Age"] = df.loc[[785, 453], "Age"] / 10